#!/usr/bin/env python
# --------------------------------------------------------------------
# Andrea Santamaria Garcia, May 2016.
# --------------------------------------------------------------------
# The script will loop through the directories of rootdir, which 
# should contain folders named 'job_number', each one containing a dump
# file generated by SixTrack. The number represents the phase trip.
# It will take all the dump files and merge them in one, filtering
# only the particle with ID=1. 
# --------------------------------------------------------------------
import os
import sys
from math import sqrt

import numpy as np

from util import GetData

# --------------------------------------------------------------------
# Input path of the simulation folders and turn
# --------------------------------------------------------------------
rootdir = sys.argv[1]
tau = float(sys.argv[2])

# --------------------------------------------------------------------
# Check if outfile exists, and if so remove it
# --------------------------------------------------------------------
outfile = 'pos_data.txt'
try:
    os.remove(outfile)
except OSError:
    pass

# --------------------------------------------------------------------
# Parameters
# --------------------------------------------------------------------
emittance_norm = 2.5e-6  # um
# --------------------------------------------------------------------
beta_x = 0.150739  # [m]
beta_y = 0.150235
# --------------------------------------------------------------------
alpha_x = 0.003485
alpha_y = -0.000764
# --------------------------------------------------------------------
gamma_x = (1 + alpha_x**2)/beta_x
gamma_y = (1 + alpha_y**2)/beta_y
# --------------------------------------------------------------------
energy = 7e12  # Beam energy at collision [eV]

# --------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------
m_p = 938.272046e6  # Proton mass [eV/c^2]
c = 299792458  # Speed of light [m/s]
gamma_rel = energy/m_p  # Relativistic gamma
beta_rel = np.sqrt(1-(1/gamma_rel**2))  # Relativistic beta
emittance_geom = emittance_norm/(beta_rel*gamma_rel)
sigma_x = np.sqrt(emittance_geom*beta_x)
sigma_y = np.sqrt(emittance_geom*beta_y)

with open(outfile,'w') as f:
    for item in os.listdir(rootdir):
        if os.path.isdir(item):
            infile = os.path.join(os.path.join(rootdir, item), 'dump.txt')
            phase = int(item.strip('job_'))
        get = GetData(infile)
        data_dict = get.data_column(column=0, regex=r'1\b')
        for turn, x, xp, y, yp in zip(data_dict[1], data_dict[3], data_dict[4], data_dict[5], data_dict[6]):
            x = float(data_dict[3])*1e-3
            xp = float(data_dict[4])*1e-3
            y = float(data_dict[5])*1e-3
            yp = float(data_dict[6])*1e-3
            # Sigma matrix for X
            term_1_x = mean(np.multiply(x,x)) - np.multiply(mean(x), mean(x))
            term_2_x = mean(np.multiply(x,xp)) - np.multiply(mean(x),mean(xp))
            term_3_x = mean(np.multiply(xp,x)) - np.multiply(mean(xp), mean(x))
            term_4_x = mean(np.multiply(xp,xp)) - np.multiply(mean(xp),mean(xp))
            # Sigma matrix for Y
            term_1_y = mean(np.multiply(y,y)) - np.multiply(mean(y), mean(y))
            term_2_y = mean(np.multiply(y,yp)) - np.multiply(mean(y),mean(yp))
            term_3_y = mean(np.multiply(yp,y)) - np.multiply(mean(yp), mean(y))
            term_4_y = mean(np.multiply(yp,yp)) - np.multiply(mean(yp),mean(yp))
            # For X
            det_x = multiply(term_1_x, term_4_x) - multiply(term_3_x, term_2_x)
            print sqrt(abs(det_x))
            # For Y
            det_y = multiply(term_1_y, term_4_y) - multiply(term_3_y, term_2_y)
            print sqrt(abs(det_y))
            # em_x = (gamma_x*x**2 + 2*alpha_x*x*xp + beta_x*xp**2)/(beta_rel*gamma_rel)
            # em_y = (gamma_y*y**2 + 2*alpha_y*y*yp + beta_y*yp**2)/(beta_rel*gamma_rel)
            # sig_x = np.sqrt(em_x*beta_x) / sigma_x
            # sig_y = np.sqrt(em_y*beta_y) / sigma_y
            f.write('%.0f %.0f %.0f %.8E %.8E %.8E %.8E %.8E %.8E \n' % (tau, phase, float(turn), float(x), float(xp), float(y), float(yp), sig_x, sig_y))

    
